# Generated by Django 2.1.1 on 2018-12-01 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TL_InstitutionLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tl_institution_levels',
            },
        ),
    ]
