from properties.app_roles import Roles

class AnnouncementConstants:

    ALLOWED_ROLES_TO_CREATE_ANNOUNCEMENT = [Roles.INSTITUTION_SUPER_USER, Roles.DIRECTOR, Roles.SCHOOL_ADMIN, Roles.PRINCIPAL, Roles.TEACHER]

    PERMISSION_DICTIONARY = {
        Roles.INSTITUTION_SUPER_USER : [Roles.INSTITUTION_SUPER_USER, Roles.DIRECTOR, Roles.BOARD_MEMBER, Roles.SCHOOL_ADMIN, Roles.PRINCIPAL, Roles.TEACHER, Roles.STUDENT, Roles.PARENT, Roles.LIBRARIAN, Roles.LAB_ASSISTANT, Roles.ACCOUNTANT, Roles.ENQUIRY_ASSISTANT, Roles.SECURITY],
        Roles.DIRECTOR : [Roles.INSTITUTION_SUPER_USER, Roles.DIRECTOR, Roles.BOARD_MEMBER, Roles.SCHOOL_ADMIN, Roles.PRINCIPAL, Roles.TEACHER, Roles.STUDENT, Roles.PARENT, Roles.LIBRARIAN, Roles.LAB_ASSISTANT, Roles.ACCOUNTANT, Roles.ENQUIRY_ASSISTANT, Roles.SECURITY],
        Roles.SCHOOL_ADMIN : [Roles.INSTITUTION_SUPER_USER, Roles.DIRECTOR, Roles.BOARD_MEMBER, Roles.SCHOOL_ADMIN, Roles.PRINCIPAL, Roles.TEACHER, Roles.STUDENT, Roles.PARENT, Roles.LIBRARIAN, Roles.LAB_ASSISTANT, Roles.ACCOUNTANT, Roles.ENQUIRY_ASSISTANT, Roles.SECURITY],
        Roles.PRINCIPAL : [Roles.INSTITUTION_SUPER_USER, Roles.DIRECTOR, Roles.BOARD_MEMBER, Roles.SCHOOL_ADMIN, Roles.PRINCIPAL, Roles.TEACHER, Roles.STUDENT, Roles.PARENT, Roles.LIBRARIAN, Roles.LAB_ASSISTANT, Roles.ACCOUNTANT, Roles.ENQUIRY_ASSISTANT, Roles.SECURITY],
        Roles.TEACHER : [Roles.STUDENT, Roles.PARENT],
    }