# Generated by Django 2.1 on 2018-11-13 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roles', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('table_name', models.CharField(max_length=100, null=True)),
                ('read_status', models.BooleanField(default=False)),
                ('can_change_read_status_direclty', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to='users.EN_Users')),
                ('created_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_to', to='users.EN_Users')),
                ('en_user_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='en_user_roles', to='roles.EN_UserRoles')),
                ('escalated_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escalated_from', to='users.EN_Users')),
            ],
            options={
                'db_table': 'en_activity',
            },
        ),
        migrations.CreateModel(
            name='EN_ActivityPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('priority', models.IntegerField(default=5)),
                ('escalation_days', models.IntegerField(default=10)),
            ],
            options={
                'db_table': 'en_activity_pattern',
            },
        ),
        migrations.AddField(
            model_name='en_activity',
            name='pattern',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pattern', to='activity.EN_ActivityPattern'),
        ),
    ]
