# Generated by Django 2.1.1 on 2019-03-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_tl_institutionlevels'),
        ('users', '0003_en_users_activation_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_AnnouncementRecipients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.CharField(max_length=255, null=True)),
                ('class_fk', models.CharField(max_length=255, null=True)),
                ('role', models.CharField(max_length=255)),
                ('organization_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.EN_OrganizationGroup')),
            ],
            options={
                'db_table': 'en_announcement_recipients',
            },
        ),
        migrations.CreateModel(
            name='EN_Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=1000)),
                ('sms_content', models.CharField(max_length=100, null=True)),
                ('date', models.DateTimeField()),
                ('priority', models.SmallIntegerField(default=3)),
                ('announced_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.EN_Users')),
            ],
            options={
                'db_table': 'en_announcements',
            },
        ),
    ]
