# Generated by Django 2.1b1 on 2018-11-29 17:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from apps.users.models import EN_Users


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Documents',
            fields=[
        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.FileField(upload_to='documents/')),
                ('unique_name', models.CharField(max_length=100, unique=True)),
                ('file_description', models.CharField(max_length=300, null=True)),
                ('tag', models.CharField(max_length=50, null=True)),
                ('type', models.CharField(max_length=30, null=True)),
                ('uploaded_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('no_of_days_to_keep_file', models.IntegerField(null=True)),
                ('uploaded_by',models.ForeignKey(EN_Users, null=False, on_delete=models.CASCADE))
            ],
            options={
                'db_table': 'en_documents',
            },
        ),
    ]
