# Generated by Django 2.1b1 on 2018-12-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
