# Generated by Django 2.1b1 on 2018-12-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20181201_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='en_documents',
            old_name='file',
            new_name='data_file',
        ),
        migrations.RenameField(
            model_name='en_documents',
            old_name='unique_name',
            new_name='name',
        ),
    ]
