# Generated by Django 2.1.2 on 2018-12-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_en_documents_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='type',
            field=models.CharField(default=2, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
