# Generated by Django 2.1.2 on 2018-12-01 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20181201_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='file_name',
            field=models.FileField(max_length=30, upload_to='documents/'),
        ),
    ]
