# Generated by Django 2.1b1 on 2018-12-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_auto_20181202_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='type',
            field=models.CharField(max_length=30),
        ),
    ]
