# Generated by Django 2.1 on 2019-01-07 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20190107_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_documents',
            name='data_file',
            field=models.FileField(max_length=500, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='is_file',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='moved_to_aws',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='parent_folder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.EN_Documents'),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='en_documents',
            name='unique_name',
            field=models.CharField(default=4, max_length=500, unique=True),
        ),
    ]
