# Generated by Django 2.1 on 2019-01-07 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20190107_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.EN_Users'),
        ),
        migrations.AlterField(
            model_name='en_documents',
            name='unique_name',
            field=models.CharField(default=16, max_length=500, unique=True),
        ),
    ]
