# Generated by Django 2.1 on 2019-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_auto_20190110_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='unique_name',
            field=models.CharField(default=76, max_length=500, unique=True),
        ),
    ]
