# Generated by Django 2.1 on 2019-01-12 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0017_auto_20190112_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_documents',
            name='is_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='en_documents',
            name='unique_name',
            field=models.CharField(default=81, max_length=500, unique=True),
        ),
    ]
