# Generated by Django 2.1.4 on 2019-01-19 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_auto_20190119_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='unique_name',
            field=models.CharField(default=92, max_length=500, unique=True),
        ),
    ]
