# Generated by Django 2.1 on 2019-03-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0021_auto_20190327_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_documents',
            name='unique_name',
            field=models.CharField(default='doc_293', max_length=500, unique=True),
        ),
    ]
