class English_DK:

    lang = {
        "key":"values",
        "user_successfully_registered" : "Successfully Registered",
        "error_not_a_post_request" : "Direct access is restricted",
        "error_session_time_out" : "Session timeout",
        "no_session_key_found" : "Sesssion Expired / No Session Key found",
        "direct_access_denied":"Direct access denied",
        "invalid_credentials":"Invalid Username/Password",
        "email_not_registered":"Not a registered Email ID" ,
        "invalid_email_id":"Not a valid Email ID" ,
        "signout_success":"Successfully Signed out" ,
        "no_such_role_for_user":"You are not assigned with this role or the role is not approved " ,
        "role_changes_successfully":"Role changes successfully" ,
        "no_privelege_to_access_app":"You dont have privelage to access this app | Change the role and try again" ,
        "org_group_created_successfully":"Successfully created new group" ,
        "unregistered_url":"Invalid URL | 404 : Page Not Found" ,
        "invalid_table_name_on_user_role":"Invalid TableName on UserRole | Contact Site Admin" ,
        "role_request_submitted_successfully":"Request submitted successfully" ,
        "role_already_exists":"Request role already exists" ,
        "invalid_product_specified":"Invalid Product Specified" ,
        "invalid_product_id_for_organization_group":"Invalid Myshishya ID For Organization Group" ,
        "invalid_product_id_for_organization":"Invalid Myshishya ID For Organization" ,
        "invalid_product_id_for_user":"Invalid Myshishya ID For User" ,
        "invalid_role_selected":"Invalid Role Selected" ,
        "cannot_set_role_as_site_admin":"Cannot set role as SiteAdmin" ,
        "organization_registration_success":"Organization Registered Successfully",
        "invalid_activity_pattern":"Invalid Activity Pattern",
        "invalid_table_id_for_activity":"Invalid Table ID for creating Activity",
        "invalid_user_id_for_activity_creation":"Invalid User ID for creating Activity",
        "user_registration_successful":"Registration Successful",
        "new_task_successfully_saved":"Successfully Added New Task",
        "task_previous_date_error":"Task cannot be created on a previous date",
        "invalid_date_entry":"Invalid date entered",
        "invalid_time_entry":"Invalid time entered",
        "task_name_is_empty":"Task cannot be empty",
        "task_with_same_constraints_already_exist":"Task already exists",
        "keep_unapproved_requests_days_not_a_number":"Days should be a number",
        "keep_unapproved_requests_days_should_be_less_than_90_days":"Days value should be less than 90",
        "invalid_role_requested_for":"Invaild Role",
        "invalid_primary_approver_role":"Invaild Primary Approver Role",
        "invalid_secondary_approver_role":"Invaild Secondary Approver Role",
        "primary_approver_lacks_permission_to_approve":"Primary approver does not have permission to approve the selected role",
        "secondary_approver_lacks_permission_to_approve":"Secondary approver does not have permission to approve the selected role",
        "successfully_added_new_role_acceptance_permission":"Successfully added new Permission",
        "no_message_body": "Please enter a text to send",
        "select_valid_user": "Please select a valid user to send a message",
        "role_permission_already_exists": "Role Permission Already Exists",
        "invalid_org_group_product_id": "Invalid Organization Group",
        "no_approved_permission_for_user_on_this_org": "You must be an approved Institution Super User for performing this action",
        "user_dont_have_any_active_inst_su_role": "You dont have any Approved Institution SuperUser Role for performing this action",
        "invalid_method_type": "Invalid Method Type",
        "missing_expected_parameters": "Cannot process request as expected parameters are missing",
        "failed_to_locate_record": "Failed to locate selected record",
        "record_deleted_successfully": "Record succesfully deleted",
        "denied_permission_to_create_activity_on_table": "Permission denied to create activity on non organization table",
        "failed_to_create_activity": "Failed to create activity | Request Deleted",
        "role_action_done_successfully": "Successfully Completed Role Request Action",
        "activity_not_assigned_to_you": "Selected activity is not assigned to you",
        "failed_role_action_approval_request": "Failed to complete role request",
        "failed_to_ignore_role_request_activity": "Failed to ignore role request activity",
        "no_users_to_approve": "No Users To Approve",
        "same_username":"Please enter a different username than your current Username",
        "username_exists_otheruser":"This Username is already taken. Kindly enter a different username",
        "successful_username_reset":"Successfully reset the username",
        "same_password":"Please enter a new password",
        "successful_pass_reset":"Successfully Reset your current password",
        "last_two_pass_error":"Your new password cannot be the same as your last two passwords",
        "invalid_characters_in_product_id_list":"Invalid Characters Found in Myshishya ID List - Allowed chars are[MY 0 to 9 and Comma (,)]",
        "parent_id_and_student_id_cannot_be_same":"Parent ID and Student ID cannot be same",
        "action_denied_for_your_current_role":"Action denied for your current role",
        "selected_role_lacks_permission_to_send_or_approve_role_request":"Current role lacks permission to send or approve role request",
        "role_request_send_or_approved_successfully":"Role request send / approve successfully",
        "missing_session_data":"Error : Session Data Missing",
        "school_start_error": "The school start time is after School End time. Please provide a correct Time",
        "breakfast_start_error": "The Breakfast start time is after Breakfast End time. Please provide a correct Time",
        "lunch_start_error": "The Lunch start time is after Lunch End time. Please provide a correct Time",
        "dinner_start_error": "The Dinner start time is after Dinner End time. Please provide a correct Time",
        "interval_end_error": "The Interval End time is after School End time. Please provide a correct Time",
        "total_period_error": "There should be atleast one period for the day",
        "interval_count_error": "Please specify at least one interval time since Interval count is not Zero",
        "interval_duration_error": "The Interval Duration cannot be Zero",
        "interval_count_warning": "You have not entered any interval count. Please make sure correct value is entered in the fields.",
        "interval_duration_warning": "You have provided interval count greater than 60 minutes. Please make sure you have entered correct value.",
        "breakfast_start_end_error": "Please enter both start and end time for breakfast",
        "lunch_start_end_error": "Please enter both start and end time for lunch",
        "dinner_start_end_error": "Please enter both start and end time for dinner",
        "unable_to_find_the_selected_role": "Unable to find the selected role",
        "already_on_the_same_role": "You are already on the same role",
        "current_role_doesnot_have_permission_to_do_this_action": "Your current role doesnt have permission to perform this action",
        "class_end_date_prior_to_start_date_error": "Class Start Date cannot be after Class End Date",
        "book_added_successfully": "Successfully added the book",
        "invalid_table_for_activity_creation": "Invalid table for activity creation",
        "failed_to_read_role_code_or_product_id": "Failed to read role_code or product_id",
        "no_active_roles_selected": "No active roles selected",
        "invalid_organization_id": "Invalid Organization ID",
        "current_role_have_no_privilage_on_selected_organization": "Current role have no privilage on selected organization",
        "no_approvers_found_for_this_organization": "No approvers found for this institution",
        "role_raised_successfully": "Role(s) raised successfully",
        "student_not_found": "Student ID Not Found",
        "selected_student_does_not_belong_to_your_school": "Selected student does not belong to your school",
        "no_get_atribute_specified": "Could not find Myshishya Id of user",
        "invalid_product_id": "Invalid Myshishya Id",
        "success_added_class": "Successfully Added class details",
        "success_added_subject": "Successfully Added Subject details",
        "current_role_cannot_perform_this_action": "Permission denied for this role",
        "no_organization_associated_to_this_role": "No Organization associated to this role",
        "no_role_change_permitted_for_site_admin": "No role change allowed for SITE ADMIN",
    }