# Generated by Django 2.1b1 on 2018-11-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_AddressBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100, null=True)),
                ('landmark', models.CharField(max_length=100, null=True)),
                ('is_current_address', models.BooleanField(default=True)),
                ('is_permanent_address', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'en_address_book',
            },
        ),
        migrations.CreateModel(
            name='EN_Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=10)),
                ('secondary_number', models.CharField(max_length=15, null=True)),
                ('is_landline_number', models.BooleanField(default=True)),
                ('email_id', models.EmailField(max_length=254, null=True, unique=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('publish_your_site', models.BooleanField(default=False)),
                ('mobile_country_code', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilities.EN_Country')),
            ],
            options={
                'db_table': 'en_contacts',
            },
        ),
        migrations.CreateModel(
            name='EN_Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=12)),
                ('date_of_birth', models.DateField()),
                ('display_picture', models.CharField(max_length=100, null=True)),
                ('newsletter_subscribe', models.BooleanField(default=True)),
                ('account_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilities.TL_AccountStatus')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.EN_Contacts')),
            ],
            options={
                'db_table': 'en_users',
            },
        ),
        migrations.CreateModel(
            name='TL_Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tl_gender',
            },
        ),
        migrations.AddField(
            model_name='en_users',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.TL_Gender'),
        ),
        migrations.AddField(
            model_name='en_addressbook',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.EN_Users'),
        ),
        migrations.AddField(
            model_name='en_addressbook',
            name='zipcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilities.EN_Zipcode'),
        ),
        migrations.AlterUniqueTogether(
            name='en_addressbook',
            unique_together={('user', 'house_name', 'zipcode', 'is_current_address', 'is_permanent_address')},
        ),
    ]
