# Generated by Django 2.1b1 on 2018-11-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_users',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
