# Generated by Django 2.1b1 on 2018-12-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181130_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_users',
            name='activation_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
