# Generated by Django 2.1 on 2018-11-14 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('volume', models.IntegerField(default=1)),
                ('book_code', models.CharField(max_length=100, null=True)),
                ('author', models.CharField(max_length=100, null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('published_year', models.IntegerField()),
            ],
            options={
                'db_table': 'en_books',
            },
        ),
        migrations.CreateModel(
            name='TL_BooksCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'db_table': 'tl_books_category',
            },
        ),
        migrations.CreateModel(
            name='TL_BooksSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.TL_BooksCategory')),
            ],
            options={
                'db_table': 'tl_books_sub_category',
            },
        ),
        migrations.AddField(
            model_name='en_books',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.TL_BooksCategory'),
        ),
        migrations.AddField(
            model_name='en_books',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='books.TL_BooksSubCategory'),
        ),
        migrations.AlterUniqueTogether(
            name='en_books',
            unique_together={('name', 'volume', 'author', 'publisher', 'published_year', 'category')},
        ),
    ]
