# Generated by Django 2.1.1 on 2018-12-01 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_tl_institutionlevels'),
        ('school_timings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
                ('batch_nick_name', models.CharField(max_length=100, null=True)),
                ('academic_starting_year', models.DateField()),
                ('academic_ending_year', models.DateField(null=True)),
                ('batch_name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.EN_Organization')),
                ('organization_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organization.TL_InstitutionLevels')),
                ('timing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='school_timings.EN_SchoolTimings')),
            ],
            options={
                'db_table': 'en_classes',
            },
        ),
        migrations.AlterUniqueTogether(
            name='en_classes',
            unique_together={('organization', 'class_name', 'academic_starting_year')},
        ),
    ]
