# Generated by Django 2.1.1 on 2018-12-25 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_tl_institutionlevels'),
        ('users', '0003_en_users_activation_token'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_classes',
            name='class_division',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='en_classes',
            name='class_teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.EN_Users'),
        ),
        migrations.AlterUniqueTogether(
            name='en_classes',
            unique_together={('organization', 'class_name', 'class_division', 'academic_starting_year')},
        ),
    ]
