# Generated by Django 2.1.4 on 2019-01-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20181225_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_classes',
            name='batch_nick_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='en_classes',
            name='class_division',
            field=models.CharField(default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='en_classes',
            name='class_name',
            field=models.CharField(max_length=30),
        ),
    ]
