# Generated by Django 2.1.1 on 2018-12-02 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_ClassSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.EN_Classes')),
            ],
            options={
                'db_table': 'en_class_subjects',
            },
        ),
        migrations.AlterUniqueTogether(
            name='en_classsubjects',
            unique_together={('class_fk', 'subject_name')},
        ),
    ]
