# Generated by Django 2.1 on 2019-03-27 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_remove_en_attendance_subject'),
        ('organization', '0002_tl_institutionlevels'),
        ('subjects', '0003_auto_20190119_0646'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100, null=True)),
                ('duration', models.IntegerField(null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.EN_Organization')),
            ],
            options={
                'db_table': 'en_subjects',
            },
        ),
        migrations.AlterUniqueTogether(
            name='en_classsubjects',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='en_classsubjects',
            name='class_fk',
        ),
        migrations.RemoveField(
            model_name='en_classsubjects',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='en_subjectteachers',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='en_subjectteachers',
            name='subject',
        ),
        migrations.DeleteModel(
            name='EN_ClassSubjects',
        ),
    ]
