# Generated by Django 2.1 on 2019-03-27 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_tl_institutionlevels'),
        ('books', '0001_initial'),
        ('subjects', '0004_auto_20190327_1114'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_SubjectBooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.EN_Books')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.EN_Organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.EN_Subjects')),
            ],
            options={
                'db_table': 'en_subject_books',
            },
        ),
    ]
