# Generated by Django 2.1 on 2019-03-27 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_tl_institutionlevels'),
        ('classes', '0003_auto_20190102_0649'),
        ('books', '0001_initial'),
        ('users', '0003_en_users_activation_token'),
        ('subjects', '0005_en_subjectbooks'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_ClassSubjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.EN_Classes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.EN_Organization')),
            ],
            options={
                'db_table': 'en_class_subjects',
            },
        ),
        migrations.AlterField(
            model_name='en_subjects',
            name='tag',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='en_subjectbooks',
            unique_together={('subject', 'book', 'organization')},
        ),
        migrations.AlterUniqueTogether(
            name='en_subjects',
            unique_together={('subject_name', 'tag', 'organization')},
        ),
        migrations.AddField(
            model_name='en_classsubjects',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.EN_Subjects'),
        ),
        migrations.AddField(
            model_name='en_subjectteachers',
            name='class_subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.EN_ClassSubjects'),
        ),
        migrations.AlterUniqueTogether(
            name='en_subjectteachers',
            unique_together={('class_subject', 'teacher')},
        ),
        migrations.AlterUniqueTogether(
            name='en_classsubjects',
            unique_together={('subject', 'class_fk', 'organization')},
        ),
    ]
