# Generated by Django 2.1 on 2019-03-27 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20190327_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_subjects',
            name='tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
