# Generated by Django 2.1b1 on 2018-11-08 18:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_LoginCredentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('password_history', models.CharField(max_length=130, null=True)),
                ('last_logged_in_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_online', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.EN_Users')),
            ],
            options={
                'db_table': 'en_login_credentials',
            },
        ),
    ]
