# Generated by Django 2.1.2 on 2018-12-01 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_SchoolTimings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timing_name', models.CharField(max_length=150)),
                ('school_starting_time', models.TimeField()),
                ('school_closing_time', models.TimeField()),
                ('breakfast_starting_time', models.TimeField(null=True)),
                ('breakfast_ending_time', models.TimeField(null=True)),
                ('lunch_starting_time', models.TimeField(null=True)),
                ('lunch_ending_time', models.TimeField(null=True)),
                ('dinner_starting_time', models.TimeField(null=True)),
                ('dinner_ending_time', models.TimeField(null=True)),
                ('no_of_periods', models.IntegerField()),
                ('first_interval_starting_time', models.TimeField(null=True)),
                ('first_interval_ending_time', models.TimeField(null=True)),
                ('second_interval_starting_time', models.TimeField(null=True)),
                ('second_interval_ending_time', models.TimeField(null=True)),
                ('third_interval_starting_time', models.TimeField(null=True)),
                ('third_interval_ending_time', models.TimeField(null=True)),
                ('fourth_interval_starting_time', models.TimeField(null=True)),
                ('fourth_interval_ending_time', models.TimeField(null=True)),
                ('assembly_on_days', models.CharField(default='[]', max_length=60)),
                ('assembly_starting_time', models.TimeField(null=True)),
                ('assembly_ending_time', models.TimeField(null=True)),
                ('off_days', models.CharField(default='[]', max_length=30)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.EN_Organization')),
            ],
            options={
                'db_table': 'en_school_timings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='en_schooltimings',
            unique_together={('organization', 'timing_name')},
        ),
    ]
