# Generated by Django 2.1 on 2018-12-04 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_timings', '0002_auto_20181204_1131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='en_schooltimings',
            name='assembly_ending_time',
        ),
        migrations.RemoveField(
            model_name='en_schooltimings',
            name='assembly_starting_time',
        ),
        migrations.AddField(
            model_name='en_schooltimings',
            name='assembly_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='en_schooltimings',
            name='assembly_on_days',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='en_schooltimings',
            name='off_days',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
