# Generated by Django 2.1 on 2018-12-04 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_timings', '0004_auto_20181204_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='en_schooltimings',
            name='off_days',
        ),
    ]
