# Generated by Django 2.1b1 on 2018-12-05 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_timings', '0005_remove_en_schooltimings_off_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='en_schooltimings',
            name='no_of_periods',
        ),
    ]
