# Generated by Django 2.1b1 on 2018-12-05 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_timings', '0006_remove_en_schooltimings_no_of_periods'),
    ]

    operations = [
        migrations.RenameField(
            model_name='en_schooltimings',
            old_name='class_on_friday',
            new_name='class_off_on_friday',
        ),
        migrations.RenameField(
            model_name='en_schooltimings',
            old_name='class_on_monday',
            new_name='class_off_on_monday',
        ),
        migrations.RenameField(
            model_name='en_schooltimings',
            old_name='class_on_saturday',
            new_name='class_off_on_saturday',
        ),
        migrations.RenameField(
            model_name='en_schooltimings',
            old_name='class_on_sunday',
            new_name='class_off_on_sunday',
        ),
        migrations.RenameField(
            model_name='en_schooltimings',
            old_name='class_on_thursday',
            new_name='class_off_on_thursday',
        ),
        migrations.RenameField(
            model_name='en_schooltimings',
            old_name='class_on_tuesday',
            new_name='class_off_on_tuesday',
        ),
        migrations.RenameField(
            model_name='en_schooltimings',
            old_name='class_on_wednesday',
            new_name='class_off_on_wednesday',
        ),
    ]
