# Generated by Django 2.1.1 on 2018-12-25 07:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
        ('subjects', '0001_initial'),
        ('users', '0003_en_users_activation_token'),
        ('organization', '0002_tl_institutionlevels'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('duration', models.IntegerField()),
                ('attendance_took_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('attendance_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.EN_Users')),
                ('attendance_for_class', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classes.EN_Classes')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='organization.EN_Organization')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='subjects.EN_ClassSubjects')),
            ],
            options={
                'db_table': 'en_attendance',
            },
        ),
        migrations.CreateModel(
            name='EN_ClassAbsentees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.EN_Attendance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.EN_Users')),
            ],
            options={
                'db_table': 'en_student_attendance',
            },
        ),
    ]
