# Generated by Django 2.1b1 on 2018-11-28 02:25

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('organization', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_RetiredUserRoles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role_id', models.IntegerField(unique=True)),
                ('request_approved_on', models.DateTimeField(default=None, null=True)),
                ('request_raised_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('related_organization', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.EN_Organization')),
                ('related_organization_group', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.EN_OrganizationGroup')),
                ('related_user', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='r_related_user', to='users.EN_Users')),
                ('request_approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='r_request_approved_by', to='users.EN_Users')),
                ('request_raised_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='r_request_raised_by', to='users.EN_Users')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='roles.TL_Roles')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.EN_Users')),
            ],
            options={
                'db_table': 'en_retired_user_roles',
            },
        ),
    ]
