# Generated by Django 2.1 on 2019-01-10 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_en_users_activation_token'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_notifications',
            name='created_by',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to='users.EN_Users'),
        ),
        migrations.AddField(
            model_name='en_notifications',
            name='created_to',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='created_to', to='users.EN_Users'),
        ),
        migrations.AlterField(
            model_name='en_notifications',
            name='notification_type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
