# Generated by Django 2.1 on 2019-01-10 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20190110_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='en_notifications',
            name='created_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_to', to='users.EN_Users'),
        ),
        migrations.AlterField(
            model_name='en_notifications',
            name='notification_type',
            field=models.CharField(max_length=50),
        ),
    ]
