# Generated by Django 2.1 on 2019-01-12 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20190110_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='en_notifications',
            old_name='read_status',
            new_name='read',
        ),
        migrations.AddField(
            model_name='en_notifications',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
