# Generated by Django 2.1b1 on 2018-11-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EN_UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_token', models.CharField(max_length=100, unique=True)),
                ('mobile_number', models.CharField(max_length=10, null=True)),
                ('secondary_number', models.CharField(max_length=15, null=True)),
                ('is_landline_number', models.BooleanField(default=True)),
                ('email_id', models.EmailField(max_length=254, null=True, unique=True)),
                ('website', models.CharField(max_length=100, null=True)),
                ('publish_your_site', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=12, null=True)),
                ('date_of_birth', models.DateField(null=True)),
                ('display_picture', models.CharField(max_length=100, null=True)),
                ('permanent_house_name', models.CharField(max_length=100, null=True)),
                ('permanent_street', models.CharField(max_length=100, null=True)),
                ('permanent_landmark', models.CharField(max_length=100, null=True)),
                ('is_current_address', models.BooleanField(default=True)),
                ('current_house_name', models.CharField(max_length=100, null=True)),
                ('current_street', models.CharField(max_length=100, null=True)),
                ('current_landmark', models.CharField(max_length=100, null=True)),
                ('username', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=25, null=True)),
                ('subscribe_for_news_letter', models.BooleanField(default=True)),
                ('current_zipcode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_zipcode', to='utilities.EN_Zipcode')),
            ],
            options={
                'db_table': 'en_user_registration',
            },
        ),
    ]
