# Generated by Django 2.1b1 on 2018-11-08 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('utilities', '0001_initial'),
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_userregistration',
            name='gender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.TL_Gender'),
        ),
        migrations.AddField(
            model_name='en_userregistration',
            name='mobile_country_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.EN_Country'),
        ),
        migrations.AddField(
            model_name='en_userregistration',
            name='permanent_zipcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='permanent_zipcode', to='utilities.EN_Zipcode'),
        ),
    ]
