# Generated by Django 2.1b1 on 2018-11-09 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0001_initial'),
        ('sign_up', '0002_auto_20181108_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='en_userregistration',
            name='current_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_area', to='utilities.EN_Zipcode'),
        ),
        migrations.AddField(
            model_name='en_userregistration',
            name='permanent_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanent_area', to='utilities.EN_Zipcode'),
        ),
        migrations.AlterField(
            model_name='en_userregistration',
            name='current_zipcode',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='en_userregistration',
            name='permanent_zipcode',
            field=models.CharField(max_length=7, null=True),
        ),
    ]
